# Generated by Django 5.2.4 on 2025-12-11 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_mahsulotlar_bepulyetkazish'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Manzil')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
            },
        ),
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales_today', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_products', models.IntegerField(default=0)),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_customers', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Statistikasi',
                'verbose_name_plural': 'Dashboard Statistikalari',
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qarz miqdori')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="To'langan summa")),
                ('due_date', models.DateField(verbose_name='Muddat')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('partially_paid', 'Qisman toʻlangan'), ('paid', 'Toʻlangan'), ('overdue', 'Muddati otgan')], default='pending', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.customer', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Qarz',
                'verbose_name_plural': 'Qarzlar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU kodi')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kirim narxi')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sotuv narxi')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdor')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('pc', 'Dona'), ('l', 'Litr'), ('pack', 'Paket')], max_length=10, verbose_name="O'lchov birligi")),
                ('min_quantity', models.DecimalField(decimal_places=2, default=5, max_digits=10, verbose_name='Minimal miqdor')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdor')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kirim narxi')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jami summa')),
                ('supplier', models.CharField(max_length=200, verbose_name="Ta'minotchi")),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Xarid sanasi')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Xarid qiluvchi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Kirim',
                'verbose_name_plural': 'Kirimlar',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdor')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sotuv narxi')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jami summa')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Karta'), ('credit', 'Nasiya')], default='cash', max_length=10, verbose_name="To'lov usuli")),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='Sotuv sanasi')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.customer', verbose_name='Mijoz')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Sotuv',
                'verbose_name_plural': 'Sotuvlar',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.DeleteModel(
            name='Mahsulotlar',
        ),
        migrations.AddField(
            model_name='debt',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.sale', verbose_name='Sotuv'),
        ),
    ]
